### PR TITLE
Make the library more usable and consistent

### PR DESCRIPTION
**Pull request by mmiszy**
Warning: This pull request contains breaking changes!

### Changelog
* got rid of old Bootstrap references
* fixed the augmentation module pattern
* renamed functions to feel more "JavaScript"
* values returned by functions are now "enum-like"
* updated README to reflect the changes
* added build script to package.json
* removed all legacy code
* added minified script to the repo

### Motivation
First of all function names didn't really work for most of the JavaScript programmers. Unlike C# community, in JS people are more used to functions names starting with lower capital letter. Thus names of the functions as well as the global object name in this library were changed (eg. `uaTools.getUserAgentString` instead of `UATOOLS.GetUserAgentString`).

Second of all values returned by functions in this library were completely arbitrary. There was no point of reference so one couldn't do simple comparison between the value returned and some kind of constants or enums. Therefore enum-like objects were added to the library. Compare these two pieces of code:
```javascript
// before
switch(UATOOLS.GetOperatingSystem()) {
    case 'Windows Phone':
        …
        break;
    case 'Firefox OS':
        …
        break;
}
```
```javascript
// now
switch(uaTools.getOperatingSystem()) {
    case uaTools.OPERATING_SYSTEMS.WINDOWS_PHONE:
        …
        break;
    case uaTools.OPERATING_SYSTEMS.FIREFOX_OS:
        …
        break;
}
```

I think all the changes listed above are for the better.
I've also created a branch of this code without breaking changes (methods are available under both old and new names): https://github.com/mmiszy/uatools.js/tree/version-1.0

### CODE REVIEW

**Comment by deltakosh** [comment]
I like the changes except the lower case. Even in JS we use upper case first letter for static functions

**Comment by deltakosh** [comment]
Enums and everything else are great improvements though

**Comment by deltakosh** [comment]
UATOOLS was in capitals because it acts as a namespace like I did for babylonjs, vorlonjs or handjs

**Comment by deltakosh** [comment]
Can you update your PR?

**Comment by mmiszy** [comment]
Yes, I'll update it later today.
* keep the upper-case naming convention because these are "static" methods
* keep the `UATOOLS` name for the library instead of `uaTools` (I personally dislike this one)

**Comment by deltakosh** [comment]
Thank you!

**Pull request closed without merging**
